# python libraries used in this file
from glob import glob
import os
from os import path
import fnmatch
import testsuite

# import scons environment variables
Import('env viking_dirs viking_libs')

# picks up all files ending with .cpp in the test folder
viking_test_sources = []
for root, dirnames, filenames in os.walk('src'):
    for filename in fnmatch.filter(filenames, '*.cpp'):
        viking_test_sources.append(path.join(root,filename))

# build all tests
for src_file in viking_test_sources:
	test_name = path.splitext(src_file)[0]
	program_path = path.join(viking_dirs['test_bin'], test_name)
	env.Program(target = program_path,
				source = src_file,
				CPPPATH = 'include',
				LIBS = viking_libs['common'])
