#include "eventsystem.h"
#include "vikingroot.h"

#include <SDL/SDL.h>

namespace vik
{

EventSystem::EventSystem(VikingRoot& root):
root(root)
{
}

void EventSystem::DispatchEvents()
{
	// Handle events generated by SDL
	SDL_Event e;
	while(SDL_PollEvent(&e))
	{
		switch(e.type)
		{
			case SDL_QUIT:
			root.EndLoop();
			return;
			default:
			break;
		}
	}
}

} // end namespace vik
