#include "viking/event/eventsystem.h"
#include "viking/core/vikingroot.h"

#include "viking/sdl/include.h"

namespace vik
{

void EventSystem::DispatchEvents()
{
	// Handle events generated by SDL
	SDL_Event e;
	while(SDL_PollEvent(&e))
	{
	    if(e.type == SDL_QUIT)
	    {
	        VikingRoot::Get().EndLoop();
	    }
	}
}

} // end namespace vik
